# Generated by Django 3.0.5 on 2020-05-03 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
