# Generated by Django 3.0.5 on 2020-05-03 20:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0003_remove_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractFinance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='description')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_receive', models.DateTimeField(verbose_name='date_receive')),
                ('repeat', models.CharField(max_length=150, verbose_name='repeat')),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('abstractfinance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.AbstractFinance')),
            ],
            bases=('finance.abstractfinance',),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('abstractfinance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.AbstractFinance')),
            ],
            bases=('finance.abstractfinance',),
        ),
    ]
