# Generated by Django 3.0.5 on 2020-05-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning',
            name='category',
            field=models.CharField(choices=[('in', 'Investments'), ('sl', 'Salary'), ('lo', 'Loans'), ('oth', 'Other')], default='oth', max_length=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('br', 'Bars'), ('cl', 'Clothing'), ('db', 'Debts'), ('oth', 'Other')], default='oth', max_length=10),
        ),
    ]
